### ISSUE TITLE
Render of react.html and vue2.html both produce errors and do not display

### ISSUE THREAD

**Issue by bam-tbf** [kristianmandrup/react-vue2-apollo-starter-kit#1]
Hello. I am looking for a seed that works with both react and vue. I have installed and started the app.

On navigating to http://localhost:3001/vue2.html I get a white screen and the following console errors:
`vue.app.js:17640[Vue warn]: Failed to mount component: template or render function not defined. 
(found in root instance)`

On navigating to http://localhost:3001/react.html I get a white screen the following console errors:
`GET http://localhost:3001/js/react.app.js 404 (Not Found)`

Can you advise how to fix? Thank you.

**Comment by kristianmandrup** [comment]
Hey, I seem to have forgotten to push my latest commit to this repo. Should "kinda work" now.
I only focused on the Vue2 part, the React files are mostly for reference.

Please talk to @vning93 from Scaphold.io. He helped me out a bit. There is still a little bug somewhere, but only related to GraphQL itself, which I don't really master yet. Let me know if you can take it the last step of the way! Very close ;)
Cheers!

**Comment by kristianmandrup** [comment]
Ah yes, I created an (almost fully) working version [here](https://github.com/kristianmandrup/vue2-apollo-scaphold)

Please work from there and let me know how it goes ;) 
Cheers!

PS: Added warning and redirection to Readme
